### PR TITLE
Improvements on Postgraduate details

### PR DESCRIPTION
**Pull request by ishanfdo18098**
TODO list:

- [x]  Add a link to the Google Form at the bottom of the postgrad page
- [x]  Use reversed list (New students will appear first)
- [x]  Hide the reg number, if it is selected as "Provisional"
- [x]  Group the students by the type of the degree (PhD, MPhil, MEng, MSc, Provisional)

Remaining 2 tasks will be done when there are some entries in the google form [Edit: done with dummy data]

image
image

### CODE REVIEW

**Comment by ishanfdo18098** [comment]
ref: #138

**Comment by ishanfdo18098** [comment]
> Shall we try with some dummy data, for now, to implement tasks 2 and 4?

Okay. Are the registration numbers for  MEng, MSc in,

- PG/MEng/25/12
- PG/MSc/22/11

format ?

> The registration number has the following formats.
> PG/MPhil/25/12
> PG/PhD/22/11

**Comment by ishanfdo18098** [comment]
> So we only have two research-based PG programs (MPhill and PhD) which don't involve any teaching. 

looks like we dont have MEng and MSc ?

**Comment by NuwanJ** [comment]
Let's assume those 2 also there and design the site. We can hide the MSc and MEng sections if no student is registered under that section.

If you didn't note yet, I changed the Google Form in such a way that the Degree program is a Dropdown menu now. We can use it to group the students

**Comment by ishanfdo18098** [comment]
> Let's assume those 2 also there and design the site. We can hide the MSc and MEng sections if no student is registered under that section.

done

> If you didn't note yet, I changed the Google Form in such a way that the Degree program is a Dropdown menu now. We can use it to group the students

Thanks for informing.

---

All tasks done

**Comment by ishanfdo18098** [comment]
image
image

**Comment by NuwanJ** [comment]
Had a merge conflict, it is resolved now and merged into the main branch

**Pull request closed without merging**
