### PR TITLE
Update e16200.html

### PR DESCRIPTION
**Pull request by sumuduliyanage**

### CODE REVIEW

**Comment by ishanfdo18098** [comment]
You have filled the google form too. Do you want to update the site with the data from google form or with this pull request ?



Data filled into the Google Form,
1/21/2022 19:38:20 | e16200@eng.pdn.ac.lk | E/16/200 | Department of Computer Engineering | Bambarawana Liyanage Sumudu Lakmali | B. L. S. Lakmali | Sumudu | Sumudu Liyanage | Miss. | e16200@eng.pdn.ac.lk | sumuduliyanage888@gmail.com |   | https://drive.google.com/file/d/1Xe_Sx0bS-683N0TZyDd_pzFUdsRjEsfq/view?usp=sharing |   | https://www.linkedin.com/in/sumudu-liyanage | https://github.com/sumuduliyanage |   |   |   |   | https://drive.google.com/open?id=1McCocTWhEK9m7Amj1ycMcFsfnSrpg4Wc |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by sumuduliyanage** [comment]
It's better if it can be done through the google form.

**Comment by ishanfdo18098** [comment]
Updated using google form data 
20ada4bc69ad6f0348106ba7f4ff8715aba08e7a - image
b7072014b718bd624383bc84b1efecdb72f4df7f - other data

**Comment by ishanfdo18098** [comment]
> It's better if it can be done through the google form.

**Comment by sumuduliyanage** [comment]
ok. thanks.

**Pull request closed without merging**
