### PR TITLE
Update biswajith-dissanayake.html

### PR DESCRIPTION
**Pull request by biswajithdissanayake**

### CODE REVIEW

**Comment by ishanfdo18098** [comment]
Please upload your profile image to `images/staff/academic-staff/biswajith-dissanayake.png`

Or send me a link to download it. I will do that ☺️

**Comment by biswajithdissanayake** [comment]
Dear Sir,
Thank you very much for your response, Kindly note that It shows that I
don't have authority to upload image files to
given location. I shall be thankful if you could check the access rights to
the folder.
Thank you.
Best regards
Biswajith Dissanayake

**Comment by ishanfdo18098** [comment]
@biswajithdissanayake Thanks for your response. Just to clarify, I'm actually a student at the university, not a lecturer. I apologize if there was any confusion.

Regarding adding your profile picture, you can follow the documentation at https://people.ce.pdn.ac.lk/documentation/change-add-staff-profile-pic/ which outlines the process. This should allow you to add the image without needing special folder access rights.

If you encounter any issues following those instructions, please let us know and we'll be happy to assist further.

**Comment by biswajithdissanayake** [comment]
Dear Ishan,
Could you please tell me why I can't access ce.pdn.ac.lk page.
I shall be thankful if you can guide me to fix this issue.
Screenshot also attached herewith.
Best regards
Biswajith
[image: image.png]

**Pull request merged**
